### ISSUE TITLE
flake: `TestServer/EphemeralDeployment`: address already in use

### ISSUE THREAD

**Issue by dannykopping** [coder/internal#658]
> Different issue seen [here](https://github.com/coder/coder/actions/runs/15402599063/job/43338538726):
> 
> ```
> === FAIL: cli TestServer/EphemeralDeployment (unknown)
>     clitest.go:75: invoking command: coder --global-config /tmp/TestServerEphemeralDeployment2857166677/001 server --http-address :0 --access-url http://example.com/ --ephemeral
>     ptytest.go:132: 2025-06-02 20:57:54.455: cmd: "Started HTTP listener at http://[::]:36265"
>     ptytest.go:132: 2025-06-02 20:57:54.455: cmd: "Using an ephemeral deployment directory (/tmp/coder_ephemeral_1748897874455)\r"
>     ptytest.go:132: 2025-06-02 20:57:54.455: cmd: "Using built-in PostgreSQL (/tmp/coder_ephemeral_1748897874455/postgres)\r"
>     ptytest.go:167: 2025-06-02 20:57:54.456: cmd: matched "Using an ephemeral deployment directory" = "Started HTTP listener at http://[::]:36265\r\nUsing an ephemeral deployment directory"
>     server_test.go:215: 2025-06-02 20:57:54.456: cmd: matched newline = " (/tmp/coder_ephemeral_1748897874455)"
>     ptytest.go:132: 2025-06-02 20:57:59.637: cmd: "Removing ephemeral deployment directory...\r"
>     ptytest.go:132: 2025-06-02 20:57:59.679: cmd: "Removed ephemeral deployment directory\r"
>     server_test.go:230: 
>         	Error Trace:	/home/runner/work/coder/coder/cli/server_test.go:230
>         	Error:      	Received unexpected error:
>         	            	running command "coder server": Failed to start built-in PostgreSQL. Optionally, specify an external deployment with `--postgres-url`:
>         	            	    github.com/coder/coder/v2/cli.startBuiltinPostgres
>         	            	        /home/runner/work/coder/coder/cli/server.go:2205
>         	            	  - could not start postgres using /tmp/coder_ephemeral_1748897874455/postgres/bin/bin/pg_ctl start -w -D /tmp/coder_ephemeral_1748897874455/postgres/data -o -p 36629:
>         	            	The files belonging to this database system will be owned by user "runner".
>         	            	This user must also own the server process.
>         	            	
>         	            	The database cluster will be initialized with locale "en_US.UTF-8".
>         	            	The default text search configuration will be set to "english".
>         	            	
>         	            	Data page checksums are disabled.
>         	            	
>         	            	creating directory /tmp/coder_ephemeral_1748[8978](https://github.com/coder/coder/actions/runs/15402599063/job/43338538726#step:13:8979)74455/postgres/data ... ok
>         	            	creating subdirectories ... ok
>         	            	selecting dynamic shared memory implementation ... posix
>         	            	selecting default max_connections ... 100
>         	            	selecting default shared_buffers ... 128MB
>         	            	selecting default time zone ... Etc/UTC
>         	            	creating configuration files ... ok
>         	            	running bootstrap script ... ok
>         	            	performing post-bootstrap initialization ... ok
>         	            	syncing data to disk ... ok
>         	            	
>         	            	Success. You can now start the database server using:
>         	            	
>         	            	    /tmp/coder_ephemeral_1748897874455/postgres/bin/bin/pg_ctl -D /tmp/coder_ephemeral_1748897874455/postgres/data -l logfile start
>         	            	
>         	            	waiting for server to start....2025-06-02 20:57:59.585 UTC [31558] LOG:  starting PostgreSQL 13.16 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit
>         	            	2025-06-02 20:57:59.585 UTC [31558] LOG:  could not bind IPv6 address "::1": Address already in use
>         	            	2025-06-02 20:57:59.585 UTC [31558] HINT:  Is another postmaster already running on port 36629? If not, wait a few seconds and retry.
>         	            	2025-06-02 20:57:59.585 UTC [31558] LOG:  could not bind IPv4 address "127.0.0.1": Address already in use
>         	            	2025-06-02 20:57:59.585 UTC [31558] HINT:  Is another postmaster already running on port 36629? If not, wait a few seconds and retry.
>         	            	2025-06-02 20:57:59.585 UTC [31558] WARNING:  could not create listen socket for "localhost"
>         	            	2025-06-02 20:57:59.585 UTC [31558] FATAL:  could not create any TCP/IP sockets
>         	            	2025-06-02 20:57:59.587 UTC [31558] LOG:  database system is shut down
>         	            	 stopped waiting
>         	            	pg_ctl: could not start server
>         	            	Examine the log output.
>         	Test:       	TestServer/EphemeralDeployment
> ``` 

 _Originally posted by @dannykopping in [#549](https://github.com/coder/internal/issues/549#issuecomment-2932531580)_

**Comment by sreya** [comment]
Seen [here](https://github.com/coder/coder/actions/runs/16304066260/job/46045756843) too I think

**Comment by zedkipp** [comment]
Closing since this should be fixed by [#20371](https://github.com/coder/coder/pull/20371). Since we have no practical way to have embedded Postgres use an ephemeral port, we had to add retries to starting embedded postgres for tests in case of a port conflict from a race condition. It's still possible (but very unlikely) that a port conflict still occurs if the race condition happens for each retry.

**Comment by spikecurtis** [comment]
Still failing. https://github.com/coder/coder/actions/runs/18907628879/job/53969696006

**Comment by zedkipp** [comment]
Interestingly it seems like a different failure mode now that there are retries to start embedded postgres. The first attempt encounters the in-use address:
```
2025-10-29T12:25:13.2149791Z         msg= stderr: 2025-10-29 12:22:15.456 [warn]  cli: failed to start embedded postgres  attempt=1  max_attempts=3  port=42215 ...
2025-10-29T12:25:13.2151172Z                  error= could not start postgres using /tmp/TestServerBuiltinPostgres3519289194/002/postgres/bin/bin/pg_ctl start -w -D /tmp/TestServerBuiltinPostgres3519289194/002/postgres/data -o -p 42215:
<snip>
2025-10-29T12:25:13.2165529Z                         waiting for server to start....2025-10-29 12:22:15.366 UTC [17958] LOG:  starting PostgreSQL 13.21 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit
2025-10-29T12:25:13.2166650Z                         2025-10-29 12:22:15.366 UTC [17958] LOG:  could not bind IPv6 address "::1": Address already in use
2025-10-29T12:25:13.2167774Z                         2025-10-29 12:22:15.366 UTC [17958] HINT:  Is another postmaster already running on port 42215? If not, wait a few seconds and retry.
2025-10-29T12:25:13.2168789Z                         2025-10-29 12:22:15.366 UTC [17958] LOG:  could not bind IPv4 address "127.0.0.1": Address already in use
2025-10-29T12:25:13.2169946Z                         2025-10-29 12:22:15.366 UTC [17958] HINT:  Is another postmaster already running on port 42215? If not, wait a few seconds and retry.
2025-10-29T12:25:13.2170937Z                         2025-10-29 12:22:15.366 UTC [17958] WARNING:  could not create listen socket for "localhost"
2025-10-29T12:25:13.2171727Z                         2025-10-29 12:22:15.366 UTC [17958] FATAL:  could not create any TCP/IP sockets
```

The second and third attempts encounter "timed out waiting for database to become available" which seem to be errors _after_ actually binding to a new port and starting creating a new database.
```
2025-10-29T12:25:13.2174598Z     t.go:106: 2025-10-29 12:22:31.323 [warn]  cli: failed to start embedded postgres  attempt=2  max_attempts=3  port=44163  error="timed out waiting for database to become available"
2025-10-29T12:25:13.2175639Z     t.go:106: 2025-10-29 12:22:31.323 [info]  cli: stderr: 2025-10-29 12:22:31.323 [warn]  cli: failed to start embedded postgres  attempt=2  max_attempts=3  port=44163  error="timed out waiting for database to become available"
2025-10-29T12:25:13.2176661Z     t.go:106: 2025-10-29 12:22:46.529 [warn]  cli: failed to start embedded postgres  attempt=3  max_attempts=3  port=44167  error="timed out waiting for database to become available"
2025-10-29T12:25:13.2177717Z     t.go:106: 2025-10-29 12:22:46.529 [info]  cli: stderr: 2025-10-29 12:22:46.529 [warn]  cli: failed to start embedded postgres  attempt=3  max_attempts=3  port=44167  error="timed out waiting for database to become available"
```

**Comment by zedkipp** [comment]
I dug more into the embedded postgres package and found that when a port discovery error occurrs, embedded-postgres does not create the database. If the data directory exists on the next attempt, embedded-postgres assumes the database has already been created. This seems to cause the timeout error. I made a change to wipe all state between retries to ensure attempts execute the same logic that creates the database (only runs in tests). I was able to verify the retries worked on Linux when removing the `testing.Testing()` check and hard-coding the port range so I could force a conflict.

Leaving this ticket open for now to monitor for any more flakes after this change.

**Comment by zedkipp** [comment]
This hasn't surfaced again in the last month, so I'm going to close this issue. Datadog says there is only two failures, which are unrelated failures from the cloudflare outage (#1176).

<img width="1552" height="663" alt="Image" src="https://github.com/user-attachments/assets/67a06091-9a6d-41d1-8a7b-af88f79959ce" />
