### ISSUE TITLE
Tasks API: Implement `POST /tasks`

### ISSUE THREAD

**Issue by mafredri** [coder/internal#898]
Implement create endpoint.

Base path: `/api/v2/organizations/{org}/members/{user}`

**Behavior**

- Body: `{ name?, template_id? | recipe_id?, parameters?: { [k]: string }, input?: string }`
- Require one of `template_id` or `recipe_id`.
- Map `input` to prompt parameter (TBD constant).
- Generate name if absent.
- Return task details.
- **MVP**: template-based creation first, recipe-based creation post-MVP.

**Request model**

- `name?`: string
- `template_id?`: uuid
- `recipe_id?`: uuid (post-MVP)
- `parameters?`: map[string]string
- `input?`: string (shorthand for prompt)

**Response model (task)**

- `id`: uuid
- `organization_id`: uuid
- `owner_id`: uuid
- `display_name`: string
- `template_id`: uuid
- `recipe_id?`: uuid (post-MVP)
- `workspace_id?`: uuid
- `status`: `queued | working | idle | paused | completed | failed`
- `created_at`, `updated_at`, `started_at?`, `completed_at?`
- `last_error?`: string

References: https://github.com/coder/internal/issues/838

**Comment by DanielleMaywood** [comment]
This has been mostly addressed in these two PRs
- https://github.com/coder/coder/pull/19280
- https://github.com/coder/coder/pull/19447

**Comment by mafredri** [comment]
@DanielleMaywood indeed, that gets us most of the way there 👍🏻.

What's I'd consider still missing is:

- The output from `POST /tasks` (i.e. a "task" rather than a workspace)
- Consider renaming prompt -> input
- Support for parameters
- Support for name

However, I don't know how important the latter two use-cases are, can probably be omitted for now.

**Comment by DanielleMaywood** [comment]
A minimal implementation of this has been achieved, tracking the remainder in https://github.com/coder/internal/issues/955
